version: "3"
services:
    web:
        env_file:
            - .env
        image: bryanjlittlefield/tugboat-php:8.3
        container_name: codespaces_web
        volumes:
            # Mount Files to Container on build
            - ./scripts/build-files:/usr/local/bin/build-files
            # Mount Apaches Log Files on Host
            - ./var/log/apache2:/var/log/apache2
            # Update this to wherever you want VS Code to mount the folder of your project
            - "..:/var/www/html"
            # Forwards the local Docker socket to the container.
            # - /var/run/docker.sock:/var/run/docker-host.sock
            # Uncomment the next line to use Docker from inside the container. See https://aka.ms/vscode-remote/samples/docker-from-docker-compose for details.
            - /var/run/docker.sock:/var/run/docker.sock
            # Mount PHP configuration file
            - ./config/php/php.ini:/usr/local/etc/php/php.ini
            # Mount SSL configuration file
            - ./config/ssh/sshd_config:/etc/ssh/sshd_config
        # network_mode: service:db - this is stopping us from pinging/access to the outside world
        restart: on-failure
        environment:
            CODESPACES: "${CODESPACES}"
            CODESPACE_NAME: "${CODESPACE_NAME}"
            GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN: "${GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN}"
            PHP_VERSION: "8.3"
            MYSQL_VERSION: "8.0"
        # command: sleep infinity
        # Uncomment the next line to use a non-root user for all processes - See https://aka.ms/vscode-remote/containers/non-root for details.
        # user: vscode
    db:
        env_file:
            - .env
        image: bryanjlittlefield/tugboat-mysql:${MYSQL_VERSION}
        container_name: codespaces_db
        # command: sleep infinity
        volumes:
            # Mount MySQL Database Files on Host
            - db-data:/var/lib/mysql
            # Mount MySQL Log Files on Host
            - ./var/log/mysql:/var/log/mysql
            # Mount MySQL Config File on Host
            - ./config/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
        restart: on-failure
    redis:
        env_file:
            - .env
        image: redis
        container_name: codespaces_redis
        volumes:
          - redis_data:/data
volumes:
  db-data:
  redis_data:
